###############################################################################
## you may need to build 'amoc-arsenal-xmpp' docker image, before running:   ##
##                                                                           ##
##     docker-compose up -d --scale amoc-worker=2                            ##
##                                                                           ##
## it can be done using this command:                                        ##
##                                                                           ##
##     docker build . -t amoc-arsenal-xmpp                                   ##
##                                                                           ##
## alternatively, a custom amoc image can be provided by setting AMOC_IMAGE  ##
## environment variable:                                                     ##
##                                                                           ##
##     AMOC_IMAGE=mongooseim/amoc-arsenal-xmpp docker-compose up -d          ##
##                                                                           ##
###############################################################################
version: "3.3"
services:
  amoc-master:
    hostname: "amoc-master"
    image: "${AMOC_IMAGE:-amoc-arsenal-xmpp}"
    ports:
      - "4000:4000"
    networks:
      - amoc-test-network
    environment:
      AMOC_GRAPHITE_HOST: '"${GRAPHITE_HOST:-host.docker.internal}"'
    healthcheck:
      test: "amoc_arsenal_xmpp status"
  amoc-worker:
    image: "${AMOC_IMAGE:-amoc-arsenal-xmpp}"
    networks:
      - amoc-test-network
    ulimits: ## ensure that we can use all the ephemeral ports
      nofile:
        soft: 66000
        hard: 66000
    environment:
      AMOC_GRAPHITE_HOST: '"${GRAPHITE_HOST:-host.docker.internal}"'
      AMOC_NODES: "['amoc_arsenal_xmpp@amoc-master']"
      AMOC_XMPP_SERVERS: '[[{host, <<"host.docker.internal">>}]]'
    entrypoint: [ "sh", "-c", 'AMOC_GRAPHITE_PREFIX="\"amoc-worker.$$HOSTNAME\"" /start_amoc.sh']
    deploy:
      mode: replicated
      replicas: 6
    healthcheck:
      test: "amoc_arsenal_xmpp status"
  graphite:
    image: "graphiteapp/graphite-statsd:1.1.10-4"
    ports:
      - "8080:80"
      - "2003:2003"
    profiles:
      - with_graphite
networks:
  amoc-test-network:
