services:

  amoc-master:
    hostname: "amoc-master"
    image: "${AMOC_IMAGE:-amoc-arsenal-xmpp}"
    pull_policy: never
    environment:
      AMOC_PROMETHEUS_IP: '{0, 0, 0, 0}'
    ports:
      - "4000:4000"
    healthcheck:
      test: "amoc_arsenal_xmpp status"

  amoc-worker:
    image: "${AMOC_IMAGE:-amoc-arsenal-xmpp}"
    pull_policy: never
    ulimits: ## ensure that we can use all the ephemeral ports
      nofile:
        soft: 66000
        hard: 66000
    environment:
      AMOC_NODES: "['amoc_arsenal_xmpp@amoc-master']"
      AMOC_XMPP_SERVERS: '[[{host, <<"host.docker.internal">>}]]'
      AMOC_PROMETHEUS_IP: '{0, 0, 0, 0}'
    deploy:
      mode: replicated
      replicas: 6
    healthcheck:
      test: "amoc_arsenal_xmpp status"

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - with_prometheus
