global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: prometheus
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: amoc-master
    static_configs:
      - targets: ["ci-amoc-master-1:9090"]
  - job_name: amoc-worker-1
    static_configs:
      - targets: ["ci-amoc-worker-1:9090"]
  - job_name: amoc-worker-2
    static_configs:
      - targets: ["ci-amoc-worker-2:9090"]
